/// T25: kg index --communities is idempotent across runs.
/// Reproduces the MOC feedback loop: previously, MOC notes generated by
/// --communities were fed back into Leiden as input, each landing in a
/// singleton community that spawned its own MOC next run → unbounded node
/// growth (17 → 21 → 24 → ...). Now MOC notes are excluded from Leiden
/// input AND have deterministic ids, so the loop is broken on both sides.
use assert_cmd::Command;
use rusqlite::Connection;
use std::path::Path;

fn copy_fixture() -> tempfile::TempDir {
    let d = tempfile::tempdir().unwrap();
    let src = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/vault-min");
    for e in walkdir::WalkDir::new(&src) {
        let e = e.unwrap();
        let rel = e.path().strip_prefix(&src).unwrap();
        let dst = d.path().join(rel);
        if e.file_type().is_dir() {
            std::fs::create_dir_all(&dst).unwrap();
        } else {
            std::fs::create_dir_all(dst.parent().unwrap()).unwrap();
            std::fs::copy(e.path(), &dst).unwrap();
        }
    }
    d
}

fn moc_count(db: &std::path::Path) -> i64 {
    let c = Connection::open(db).unwrap();
    c.query_row(
        "SELECT count(*) FROM notes WHERE path LIKE 'notes/moc/%'",
        [],
        |r| r.get(0),
    )
    .unwrap()
}

fn total_nodes(db: &std::path::Path) -> i64 {
    let c = Connection::open(db).unwrap();
    c.query_row("SELECT count(*) FROM notes", [], |r| r.get(0))
        .unwrap()
}

fn run_index(d: &tempfile::TempDir) {
    Command::cargo_bin("kg")
        .unwrap()
        .env("KGX_LLM", "mock")
        .args(["index", "--full", "--communities"])
        .current_dir(d.path())
        .assert()
        .success();
}

#[test]
fn t25_communities_moc_idempotent() {
    let d = copy_fixture();
    let brain = d.path().join(".brain/.kg/brain.sqlite");

    // Run 1: fresh vault. Community MOCs are written to disk AFTER the
    // brain build, so the run-1 brain does NOT yet contain them — only
    // the pre-existing fixture MOC (datastore-moc.md). This is expected.
    // The MOC files are now on disk for run 2 to pick up.
    run_index(&d);

    // Run 2: rebuild from the same on-disk vault (which now contains the
    // community MOC files run 1 wrote). The brain now sees them. This is
    // the "steady state" baseline.
    std::fs::remove_dir_all(d.path().join(".brain/.kg")).unwrap();
    run_index(&d);
    let n2 = moc_count(&brain);
    let nodes2 = total_nodes(&brain);
    assert!(
        n2 >= 4,
        "run 2 brain must include the community MOCs written in run 1 (got {n2})"
    );

    // Run 3: same vault, .kg NOT deleted. THE KEY ASSERTION — previously
    // this grew unboundedly (17 → 21 → 25 → ...) because MOC notes fed
    // back into Leiden spawned new singleton communities, each spawning
    // its own MOC. Now MOC notes are excluded from Leiden input AND have
    // deterministic ids, so the steady state is stable.
    run_index(&d);
    let n3 = moc_count(&brain);
    let nodes3 = total_nodes(&brain);
    assert_eq!(
        n3, n2,
        "MOC count must be stable in steady state (got {n2} then {n3})"
    );
    assert_eq!(
        nodes3, nodes2,
        "total node count must be stable in steady state (got {nodes2} then {nodes3})"
    );

    // Run 4: belt-and-suspenders — one more run must also hold.
    run_index(&d);
    let n4 = moc_count(&brain);
    let nodes4 = total_nodes(&brain);
    assert_eq!(n4, n3, "fourth run MOC count drifted");
    assert_eq!(nodes4, nodes3, "fourth run node count drifted");
}
